// Generates migrations/seed/season-1.sql from the legacy corpus.
//
// Season 1 is loaded through analyzeUpload() — the exact code path a browser upload
// takes — rather than a bespoke importer, so the port is exercised by 14 real games
// before any of it is deployed.
//
// The generated SQL is committed: it is reviewable, replayable into a fresh local D1,
// and doubles as the restore procedure.
//
// Usage:  node --experimental-strip-types scripts/import-legacy.ts [--out <path>]

import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { gzipSync } from 'node:zlib';

import { buildSeasonSnapshot } from '../src/lib/mssb/aggregate.ts';
import { stadiumIdByName } from '../src/lib/mssb/reference.ts';
import { loadLegacySeason, REPO_ROOT } from '../test/legacy.ts';

const NOW = Math.floor(Date.parse('2026-09-10T00:00:00Z') / 1000);
const SEASON_ID = 1;
const IMPORTER = 'import-legacy';

const q = (s: string): string => `'${s.replace(/'/g, "''")}'`;
const nullable = (v: string | number | null | undefined): string =>
  v === null || v === undefined ? 'NULL' : typeof v === 'number' ? String(v) : q(v);

function main(): void {
  const outFlag = process.argv.indexOf('--out');
  const outPath =
    outFlag >= 0
      ? process.argv[outFlag + 1]
      : join(REPO_ROOT, 'web/migrations/seed/season-1.sql');

  const { input, roundReport } = loadLegacySeason();

  // --- the round-assignment table, for a human to eyeball once ---------------------
  console.log('\nRound assignment (resolved by team pairing, in date order):\n');
  console.log('  round  matchup                                          score   file');
  for (const r of roundReport) {
    const pairing = `${r.away} @ ${r.home}`;
    console.log(
      `  ${String(r.round ?? '?').padStart(5)}  ${pairing.padEnd(46)}  ` +
        `${r.score.padEnd(6)}  ${r.file}`,
    );
    for (const w of r.warnings) console.log(`         ! ${w}`);
  }

  const unassigned = roundReport.filter((r) => r.round === null);
  if (unassigned.length) {
    console.error(`\nERROR: ${unassigned.length} game(s) could not be assigned a round.`);
    process.exit(1);
  }

  // --- ids ------------------------------------------------------------------------
  const teamId = new Map(input.teams.map((t, i) => [t.name, i + 1]));
  const roundId = new Map(input.schedule.map((r, i) => [r.round, i + 1]));

  type MatchupKey = string;
  const matchupId = new Map<MatchupKey, number>();
  const key = (round: number, away: string, home: string): MatchupKey =>
    `${round}|${away}|${home}`;

  const lines: string[] = [];
  const say = (s = '') => lines.push(s);

  say('-- Season 1 seed, generated by scripts/import-legacy.ts. Do not edit by hand.');
  say(`-- ${input.games.length} games, ${input.teams.length} teams, ${input.schedule.length} rounds.`);
  say('');
  // No BEGIN TRANSACTION/COMMIT: remote D1 rejects explicit transaction statements in an
  // imported file (it manages the transaction itself). Local D1 tolerates them, so this
  // only shows up against --remote.

  say('INSERT INTO seasons (id, slug, name, short_label, start_date, rounds, status, is_current, created_at, updated_at)');
  say(
    `VALUES (${SEASON_ID}, ${q(input.season.slug)}, ${q(input.season.name)}, ` +
      `${q(input.season.shortLabel)}, ${q(input.season.startDate)}, ${input.season.rounds}, ` +
      `'complete', 1, ${NOW}, ${NOW});`,
  );
  say('');

  say('INSERT INTO teams (id, season_id, slug, name, color, captain_char_id, stadium_id, sort_order, created_at, updated_at) VALUES');
  say(
    input.teams
      .map((t, i) => {
        const stadium = stadiumIdByName.get(t.stadium);
        if (stadium === undefined) throw new Error(`unknown stadium "${t.stadium}"`);
        return (
          `  (${teamId.get(t.name)}, ${SEASON_ID}, ${q(t.slug)}, ${q(t.name)}, ${q(t.color)}, ` +
          `${t.captainCharId}, ${stadium}, ${i}, ${NOW}, ${NOW})`
        );
      })
      .join(',\n') + ';',
  );
  say('');

  say('INSERT INTO roster_slots (season_id, team_id, char_id, is_captain) VALUES');
  say(
    input.teams
      .flatMap((t) =>
        t.roster.map(
          (m) =>
            `  (${SEASON_ID}, ${teamId.get(t.name)}, ${m.charId}, ${m.captain ? 1 : 0})`,
        ),
      )
      .join(',\n') + ';',
  );
  say('');

  say('INSERT INTO rounds (id, season_id, round_no) VALUES');
  say(
    input.schedule
      .map((r) => `  (${roundId.get(r.round)}, ${SEASON_ID}, ${r.round})`)
      .join(',\n') + ';',
  );
  say('');

  // teams.json stores each matchup as [away, home] — verified against round 1, whose
  // ["Booty Barn","Flame Imp"] is the file booty-barn-vs-flame-imp. Reversing this
  // would silently invert the entire season's home-field advantage.
  const matchupRows: string[] = [];
  let nextMatchupId = 1;
  for (const r of input.schedule) {
    r.matchups.forEach(([away, home], slot) => {
      const id = nextMatchupId++;
      matchupId.set(key(r.round, away, home), id);
      matchupRows.push(
        `  (${id}, ${SEASON_ID}, ${roundId.get(r.round)}, ${slot}, ` +
          `${teamId.get(away)}, ${teamId.get(home)})`,
      );
    });
  }
  say('INSERT INTO matchups (id, season_id, round_id, slot, away_team_id, home_team_id) VALUES');
  say(matchupRows.join(',\n') + ';');
  say('');

  // --- games, with the original uploads preserved ----------------------------------
  const fileByGameId = new Map(roundReport.map((r) => [r.file, r]));
  let rawId = 0;

  for (const [i, g] of input.games.entries()) {
    const report = roundReport[i];
    const rawPath = join(REPO_ROOT, report.file);
    const rawBytes = readFileSync(rawPath);
    const gz = gzipSync(rawBytes, { level: 9 });
    const sha = createHash('sha256').update(rawBytes).digest('hex');
    rawId++;

    if (!fileByGameId.has(report.file)) throw new Error(`lost track of ${report.file}`);

    say(`-- ${g.away} ${g.awayScore} @ ${g.homeScore} ${g.home}  (round ${g.round})`);
    say('INSERT INTO game_raw (id, season_id, rio_game_id, sha256, filename, bytes_gz, size_raw, size_gz, was_decoded, uploaded_at, uploaded_by)');
    say(
      `VALUES (${rawId}, ${SEASON_ID}, ${q(g.gameId)}, ${q(sha)}, ` +
        `${q(report.file.split('/').pop()!)}, X'${gz.toString('hex')}', ` +
        `${rawBytes.length}, ${gz.length}, 0, ${NOW}, ${q(IMPORTER)});`,
    );

    const matchup =
      matchupId.get(key(g.round!, g.away, g.home)) ??
      matchupId.get(key(g.round!, g.home, g.away)) ??
      null;

    say('INSERT INTO games (season_id, rio_game_id, round_id, matchup_id, away_team_id, home_team_id, away_score, home_score, innings_played, stadium_id, played_at, detection, box_json, raw_id, source_name, uploaded_by, uploaded_at)');
    say(
      `VALUES (${SEASON_ID}, ${q(g.gameId)}, ${roundId.get(g.round!)}, ${nullable(matchup)}, ` +
        `${teamId.get(g.away)}, ${teamId.get(g.home)}, ${g.awayScore}, ${g.homeScore}, ` +
        `${g.innings}, ${g.stadiumId}, ${g.date}, ` +
        `${q(JSON.stringify({ source: 'legacy-import' }))}, ` +
        `${q(JSON.stringify(g.boxscore))}, ${rawId}, ${q(report.file)}, ${q(IMPORTER)}, ${NOW});`,
    );
    say('');
  }

  // Ship a prebuilt snapshot so a freshly seeded database serves from the stored row at
  // version 1, rather than rebuilding per request at version 0 (which would also mean an
  // edge cache key that never changes).
  const snapshot = buildSeasonSnapshot(input, { includeBoxscores: false });
  say('-- Prebuilt season snapshot (what every public page reads).');
  say('INSERT INTO season_snapshots (season_id, version, built_at, etag, payload)');
  say(
    `VALUES (${SEASON_ID}, 1, ${NOW}, ${q(`${input.season.slug}-1`)}, ` +
      `${q(JSON.stringify(snapshot))});`,
  );
  say('');


  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, lines.join('\n'));

  const bytes = Buffer.byteLength(lines.join('\n'));
  const longest = Math.max(...lines.map((l) => Buffer.byteLength(l)));
  console.log(`\nWrote ${outPath}`);
  console.log(`  ${input.games.length} games, ${(bytes / 1024).toFixed(0)} KB total`);
  console.log(`  longest statement line: ${(longest / 1024).toFixed(1)} KB (D1 limit is 100 KB)`);
  if (longest > 100_000) {
    console.error('  ERROR: a statement exceeds D1’s 100 KB limit.');
    process.exit(1);
  }
}

main();
